name: Deploy ChatAppBackend
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t nikhil2523/chat-app-backend
      - name: Publish Image to docker hub
        run: docker push nikhil2523/chat-app-backend
 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull nikhil2523/chat-app-backend
      - name: Delete old container
        run: docker rm -f nikhil2523/chat-app-backend
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 -- name nikhil2523/chat-app-backend